# Generated by Django 5.0.1 on 2024-02-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Staff",
            new_name="Staffs",
        ),
        migrations.RenameModel(
            old_name="Student",
            new_name="Students",
        ),
        migrations.AlterField(
            model_name="subjects",
            name="course_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.courses",
            ),
        ),
    ]
